/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.kivanval;

import static org.junit.jupiter.api.Assertions.*;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

/** A simple unit test for the 'io.kivanval.greeting' plugin. */
class GradleAvrohuggerPluginTest {
  @Test
  void pluginRegistersATask() {
    // Create a test project and apply the plugin
    Project project = ProjectBuilder.builder().build();
    project.getPlugins().apply("io.kivanval.gradle-avrohugger");

    // Verify the result
    assertNotNull(project.getTasks().findByName("generateAvroScala"));
  }
}
