/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.kivanval;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import org.apache.commons.io.FileUtils;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/** A simple functional test for the 'io.kivanval.greeting' plugin. */
class GradleAvrohuggerPluginFunctionalTest {
  @TempDir File projectDir;

  private File getBuildFile() {
    return new File(projectDir, "build.gradle");
  }

  private File getSettingsFile() {
    return new File(projectDir, "settings.gradle");
  }

  @Test
  void canRunTask() throws IOException {
    writeString(getSettingsFile(), "");
    writeString(getBuildFile(), "plugins {" + "  id('io.kivanval.gradle-avrohugger')" + "}");

    // Run the build
    GradleRunner runner = GradleRunner.create();
    runner.forwardOutput();
    runner.withPluginClasspath();
    runner.withArguments("generateAvroScala");
    runner.withProjectDir(projectDir);
    BuildResult result = runner.build();

    // Verify the result
    assertTrue(result.getOutput().contains("Hello from plugin 'io.kivanval.greeting'"));
  }

  private void writeString(File file, String string) throws IOException {
    FileUtils.write(file, string, StandardCharsets.UTF_8);
  }
}
