/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.kivanval;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/** A simple 'hello world' plugin. */
public class GradleAvrohuggerPlugin implements Plugin<Project> {
  public void apply(Project project) {
    // Register a task
    project
        .getTasks()
        .register(
            "generateAvroScala",
            task ->
                task.doLast(s -> System.out.println("Hello from plugin 'io.kivanval.greeting'")));
  }
}
